spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: zw5058143
      url: jdbc:mysql://192.168.0.104:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env: dev4

girl:
  name: 小明bbqgithub-Hello World!Code KAFKA RabbitMQ SpringBoot Netty RocketmQ hadoop spark storm flink mapReduce
  age: 12
